const nameMap = {
  1: {
    cnName: '两数之和',
    enName: 'Two Sum',
    difficulty: 'Easy',
    label: '哈希',
    hasThinkings: 'true',
  },
  2: {
    cnName: '两数相加',
    enName: 'Add Two Numbers',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'true',
  },
  3: {
    cnName: '无重复字符的最长子串',
    enName: 'Longest Substring Without Repeating Characters',
    difficulty: 'Medium',
    label: '滑动窗口',
    hasThinkings: 'true',
  },
  4: {
    cnName: '两个排序数组的中位数',
    enName: 'Median of Two Sorted Arrays',
    difficulty: 'Hard',
    label: '数组',
    hasThinkings: 'true',
  },
  5: {
    cnName: '最长回文子串',
    enName: 'Longest Palindromic Substring',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'true',
  },
  6: {
    cnName: 'Z 字形变换',
    enName: 'ZigZag Conversion',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  7: {
    cnName: '翻转整数',
    enName: 'Reverse Integer',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  8: {
    cnName: '字符串转为整数',
    enName: 'String to Integer (atoi)',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  9: {
    cnName: '回文数字',
    enName: 'Palindrome Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  10: {
    cnName: '正则表达式匹配',
    enName: 'Regular Expression Matching',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  11: {
    cnName: '盛最多水的容器',
    enName: 'Container With Most Water',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'true',
  },
  12: {
    cnName: '整数转罗马数字',
    enName: 'Integer to Roman',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  13: {
    cnName: '罗马数字转整数',
    enName: 'Roman to Integer',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  14: {
    cnName: '最长共同前缀',
    enName: 'Longest Common Prefix',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'true',
  },
  15: {
    cnName: '三数之和',
    enName: '3 Sum',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'true',
  },
  16: {
    cnName: '最接近的三数之和',
    enName: '3 Sum Closest',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  17: {
    cnName: '电话号码的字母组合',
    enName: 'Letter Combinations of a Phone Number',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  18: {
    cnName: '四数之和',
    enName: '4 Sum',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  19: {
    cnName: '删除链表的倒数第 N 个节点',
    enName: 'Remove Nth Node From End of List',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  20: {
    cnName: '有效的括号',
    enName: 'Valid Parentheses',
    difficulty: 'Easy',
    label: '栈',
    hasThinkings: 'true',
  },
  21: {
    cnName: '合并两个有序链表',
    enName: 'Merge Two Sorted Lists',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  22: {
    cnName: '生成括号',
    enName: 'Generate Parentheses',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  23: {
    cnName: '合并 K 个排序链表',
    enName: 'Merge k Sorted Lists',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  24: {
    cnName: '两两交换链表中的节点',
    enName: 'Swap Nodes In Pairs',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  25: {
    cnName: '每 k 个一组翻转链表',
    enName: 'Reverse Nodes in k-Group',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  26: {
    cnName: '从有序数组中删除重复项',
    enName: 'Remove Duplicates from Sorted Array',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'true',
  },
  27: {
    cnName: '移除元素',
    enName: 'Remove Element',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'true',
  },
  28: {
    cnName: '实现 strStr()',
    enName: 'Implement strStr()',
    difficulty: 'Easy',
    label: 'KMP算法',
    hasThinkings: 'true',
  },
  29: {
    cnName: '两数相除',
    enName: 'Divide Two Integers',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  30: {
    cnName: '串联所有单词的子串',
    enName: 'Substring with Concatenation of All Words',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  31: {
    cnName: '下一个排列',
    enName: 'Next-permutation',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  32: {
    cnName: '最长有效括号',
    enName: 'Longest Valid Parentheses',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  33: {
    cnName: '在旋转有序数组中搜索',
    enName: 'Search in Rotated Sorted Array',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  34: {
    cnName: '搜索范围',
    enName: 'Search for a Range',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  35: {
    cnName: '搜索插入位置',
    enName: 'Search Insert Position',
    difficulty: 'Easy',
    label: '二分查找',
    hasThinkings: 'true',
  },
  36: {
    cnName: '验证数独',
    enName: 'Valid Sudoku',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  37: {
    cnName: '解数独',
    enName: 'Sudoku Solver',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  38: {
    cnName: '数数并说',
    enName: 'Count and Say',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  39: {
    cnName: '组合之和',
    enName: 'Combination Sum',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  40: {
    cnName: '组合之和 II',
    enName: 'Combination Sum II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  41: {
    cnName: '缺失的第一个正数',
    enName: 'First Missing Positive',
    difficulty: 'Hard',
    label: '数组',
    hasThinkings: 'true',
  },
  42: {
    cnName: '接雨水',
    enName: 'Trapping Rain Water',
    difficulty: 'Hard',
    label: '双指针',
    hasThinkings: 'true',
  },
  43: {
    cnName: '字符串相乘',
    enName: 'Multiply String',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  44: {
    cnName: '通配符匹配',
    enName: 'Wildcard Matching',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  45: {
    cnName: '跳跃游戏 II',
    enName: 'Jump Game II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  46: {
    cnName: '全排列',
    enName: 'Permutations',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  47: {
    cnName: '全排列 II',
    enName: 'Permutations II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  48: {
    cnName: '旋转图像',
    enName: 'Rotate Image',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  49: {
    cnName: '字母异位词分组',
    enName: 'Group Anagrams',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'true',
  },
  50: {
    cnName: 'Pow(x, n)',
    enName: 'Pow(x, n)',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  51: {
    cnName: 'N 皇后',
    enName: 'N-Queens',
    difficulty: 'Hard',
    label: '回溯',
    hasThinkings: 'true',
  },
  52: {
    cnName: 'N 皇后 II',
    enName: 'N-Queens II',
    difficulty: 'Hard',
    label: '回溯',
    hasThinkings: 'true',
  },
  53: {
    cnName: '最大子数组和',
    enName: 'Maximum Subarray',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'true',
  },
  54: {
    cnName: '螺旋矩阵',
    enName: 'Spiral Matrix',
    difficulty: 'Medium',
    label: '矩阵',
    hasThinkings: 'true',
  },
  55: {
    cnName: '跳跃游戏',
    enName: 'Jump Game',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  56: {
    cnName: '合并区间',
    enName: 'Merge Intervals',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'true',
  },
  57: {
    cnName: '插入区间',
    enName: 'Insert Interval',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  58: {
    cnName: '最后一个单词的长度',
    enName: 'Length of Last Word',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'true',
  },
  59: {
    cnName: '螺旋矩阵 II',
    enName: 'Spiral Matrix II',
    difficulty: 'Medium',
    label: '矩阵',
    hasThinkings: 'true',
  },
  60: {
    cnName: '排列序列',
    enName: 'Permutation Sequence',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  61: {
    cnName: '旋转链表',
    enName: 'Rotate List',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  62: {
    cnName: '不同路径',
    enName: 'Unique Paths',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  63: {
    cnName: '不同路径 II',
    enName: 'Unique Paths II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  64: {
    cnName: '最小路径和',
    enName: 'Minimum Path Sum',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  65: {
    cnName: '有效数字',
    enName: 'Valid Number',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  66: {
    cnName: '加一',
    enName: 'Plus One',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'true',
  },
  67: {
    cnName: '二进制求和',
    enName: 'Add Binary',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'true',
  },
  68: {
    cnName: '文本左右对齐',
    enName: 'Text Justification',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  69: {
    cnName: 'x 的平方根',
    enName: 'Sqrt(x)',
    difficulty: 'Easy',
    label: '二分法',
    hasThinkings: 'true',
  },
  70: {
    cnName: '爬楼梯',
    enName: 'Climbing Stairs',
    difficulty: 'Easy',
    label: '动态规划',
    hasThinkings: 'true',
  },
  71: {
    cnName: '简化路径',
    enName: 'Simplify Path',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  72: {
    cnName: '编辑距离',
    enName: 'Edit Distance',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  73: {
    cnName: '矩阵置零',
    enName: 'Set Matrix Zeroes',
    difficulty: 'Medium',
    label: '矩阵',
    hasThinkings: 'true',
  },
  74: {
    cnName: '搜索二维矩阵',
    enName: 'Search a 2D Matrix',
    difficulty: 'Medium',
    label: '矩阵',
    hasThinkings: 'true',
  },
  75: {
    cnName: '颜色分类',
    enName: 'Sort Colors',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  76: {
    cnName: '最小覆盖子串',
    enName: 'Minimum Window Substring',
    difficulty: 'Hard',
    label: '子串',
    hasThinkings: 'true',
  },
  77: {
    cnName: '组合',
    enName: 'Combinations',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  78: {
    cnName: '子集',
    enName: 'Subsets',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  79: {
    cnName: '单词搜索',
    enName: 'Word Search',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  80: {
    cnName: '删除排序数组中的重复项 II',
    enName: 'Remove Duplicates from Sorted Array II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  81: {
    cnName: '搜索旋转排序数组 II',
    enName: 'Searching Rotated Sorted Array II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  82: {
    cnName: '删除排序链表中的重复元素 II',
    enName: 'Remove Duplicate From Sorted List II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  83: {
    cnName: '删除排序链表中的重复元素',
    enName: 'Remove Duplicates from Sorted List',
    difficulty: 'Easy',
    label: '链表',
    hasThinkings: 'true',
  },
  84: {
    cnName: '柱状图中最大的矩形',
    enName: 'Largest Rectangle in Histogram',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  85: {
    cnName: '最大矩形',
    enName: 'Maximal Rectangle',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  86: {
    cnName: '分隔链表',
    enName: 'Partition List',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  87: {
    cnName: '扰乱字符串',
    enName: 'Scramble String',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'true',
  },
  88: {
    cnName: '合并两个有序数组',
    enName: 'Merge Sorted Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  89: {
    cnName: '格雷编码',
    enName: 'Gray Code',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  90: {
    cnName: '子集 II',
    enName: 'Subsets II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  91: {
    cnName: '解码方法',
    enName: 'Decode Ways',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  92: {
    cnName: '反转链表 II',
    enName: 'Reverse Linked List II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  93: {
    cnName: '复原 IP 地址',
    enName: 'Restore Ip Address',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  94: {
    cnName: '二叉树的中序遍历',
    enName: 'Binary Tree Inorder Traversal',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  95: {
    cnName: '不同的二叉搜索树 II',
    enName: 'Unique Binary Search Trees II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  96: {
    cnName: '不同的二叉搜索树',
    enName: 'Unique Binary Search Trees',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  97: {
    cnName: '交错字符串',
    enName: 'Interleaving String',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  98: {
    cnName: '验证搜索二叉树',
    enName: 'Validate Binary Search Tree',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  99: {
    cnName: '恢复搜索二叉树',
    enName: 'Recover Binary Search Tree',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  100: {
    cnName: '相同的树',
    enName: 'Same Tree',
    difficulty: 'Easy',
    label: '二叉树',
    hasThinkings: 'true',
  },
  101: {
    cnName: '对称二叉树',
    enName: 'Symmetric Tree',
    difficulty: 'Easy',
    label: 'BFS',
    hasThinkings: 'true',
  },
  102: {
    cnName: '二叉树的层序遍历',
    enName: 'Binary Tree Level Order Traversal',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  103: {
    cnName: '二叉树的锯齿形层序遍历',
    enName: 'Binary Tree Zigzag Level Order Traversal',
    difficulty: 'Medium',
    label: 'BFS',
    hasThinkings: 'false',
  },
  104: {
    cnName: '二叉树最大深度',
    enName: 'Maximum Depth of Binary Tree',
    difficulty: 'Easy',
    label: 'DFS',
    hasThinkings: 'false',
  },
  105: {
    cnName: '从前序与中序遍历序列构造二叉树',
    enName: 'Construct Binary Tree from Preorder and Inorder Traversal',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  106: {
    cnName: '从中序与后序遍历序列构造二叉树',
    enName: 'Construct Binary Tree from In order and Post order Traversal',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  107: {
    cnName: '二叉树的层次遍历 II',
    enName: 'Binary Tree Level Order Traversal II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  108: {
    cnName: '将有序数组转换成二叉搜索树',
    enName: 'Convert Sorted Array to Binary Search Tree',
    difficulty: 'Easy',
    label: '分治',
    hasThinkings: 'true',
  },
  109: {
    cnName: '将有序数组转换为二叉搜索树',
    enName: 'Convert Sorted Array to Binary Search Tree',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  110: {
    cnName: '平衡二叉树',
    enName: 'Balanced Binary Tree',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  111: {
    cnName: '二叉树的最小深度',
    enName: 'Minimum Depth of Binary Tree',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  112: {
    cnName: '路径总和',
    enName: 'Path Sum',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  113: {
    cnName: '路径总和 II',
    enName: 'Path Sum II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  114: {
    cnName: '二叉树展开为链表',
    enName: 'Flat Binary Tree to Linked List',
    difficulty: 'Medium',
    label: '二叉树',
    hasThinkings: 'false',
  },
  115: {
    cnName: '不同的子序列',
    enName: 'Distinct Subsequences',
    difficulty: 'Hard',
    label: '动态规划',
    hasThinkings: 'false',
  },
  116: {
    cnName: '填充每个节点的下一个右侧节点指针',
    enName: 'Populating Next Right Pointers in Each Node',
    difficulty: 'Medium',
    label: '层序遍历',
    hasThinkings: 'false',
  },
  117: {
    cnName: '填充每个节点的下一个右侧节点指针 II',
    enName: 'Populating Next Right Pointers in Each Node II',
    difficulty: 'Medium',
    label: '层次遍历',
    hasThinkings: 'false',
  },
  118: {
    cnName: '杨辉三角',
    enName: 'Pascals Triangle',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  119: {
    cnName: '杨辉三角 II',
    enName: 'Pascals Triangle II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  120: {
    cnName: '三角形最小路径和',
    enName: 'Triangle',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  121: {
    cnName: '买卖股票的最佳时机',
    enName: 'Best Time to Buy and Sell Stock',
    difficulty: 'Easy',
    label: '动态规划',
    hasThinkings: 'false',
  },
  122: {
    cnName: '股票买卖的最佳时机 II',
    enName: 'Best Time to Buy and Sell Stock II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  124: {
    cnName: '二叉树中的最大路径和',
    enName: 'Binary Tree Maximum Path Sum',
    difficulty: 'Hard',
    label: '二叉树',
    hasThinkings: 'false',
  },
  125: {
    cnName: '验证回文串',
    enName: 'Is Palindrome',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  127: {
    cnName: '单词接龙',
    enName: 'Word Ladder',
    difficulty: 'Hard',
    label: 'BFS',
    hasThinkings: 'false',
  },
  128: {
    cnName: '最长连续序列',
    enName: 'Longest Consecutive Sequence',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  129: {
    cnName: '求根到叶子节点数字之和',
    enName: 'Sum Root to Leaf Numbers',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  130: {
    cnName: '被围绕的区域',
    enName: 'Surrounded Regions',
    difficulty: 'Medium',
    label: 'DFS',
    hasThinkings: 'false',
  },
  131: {
    cnName: '分隔回文串',
    enName: 'Palindrome Partitioning',
    difficulty: 'Medium',
    label: '回溯',
    hasThinkings: 'false',
  },
  133: {
    cnName: '克隆图',
    enName: 'Clone Graph',
    difficulty: 'Medium',
    label: 'DFS',
    hasThinkings: 'false',
  },
  134: {
    cnName: '加油站',
    enName: 'Gas Station',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  136: {
    cnName: '只出现一次的数字',
    enName: 'Single Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  137: {
    cnName: '只出现一次的数字 II',
    enName: 'Single Number II',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  138: {
    cnName: '随机链表的复制',
    enName: 'Copy List with Random Pointer',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  139: {
    cnName: '单词拆分',
    enName: 'Word Break',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  140: {
    cnName: '单词拆分 II',
    enName: 'Word Break II',
    difficulty: 'Hard',
    label: '记忆化搜索',
    hasThinkings: 'false',
  },
  141: {
    cnName: '环形链表',
    enName: 'Linked List Cycle',
    difficulty: 'Easy',
    label: '双指针、哈希',
    hasThinkings: 'true',
  },
  142: {
    cnName: '环形链表 II',
    enName: 'Linked List Cycle II',
    difficulty: 'Medium',
    label: '双指针、哈希',
    hasThinkings: 'false',
  },
  143: {
    cnName: '重排链表',
    enName: 'Reorder List',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'false',
  },
  144: {
    cnName: '二叉树的前序遍历',
    enName: 'Binary Tree Preorder Traversal',
    difficulty: 'Easy',
    label: '二叉树、栈',
    hasThinkings: 'false',
  },
  145: {
    cnName: '二叉树的后序遍历',
    enName: 'Binary Tree Postorder Traversal',
    difficulty: 'Easy',
    label: '二叉树、栈',
    hasThinkings: 'false',
  },
  146: {
    cnName: 'LRU 缓存',
    enName: 'LRU Cache',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  147: {
    cnName: '对链表进行插入排序',
    enName: 'Insertion Sort List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  148: {
    cnName: '排序链表',
    enName: 'Sort List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  149: {
    cnName: '直线上最多的点',
    enName: 'Max Points on a Line',
    difficulty: 'Hard',
    label: '哈希',
    hasThinkings: 'false',
  },
  150: {
    cnName: '逆波兰表达式求值',
    enName: 'Evaluate Reverse Polish Notation',
    difficulty: 'Medium',
    label: '栈',
    hasThinkings: 'false',
  },
  151: {
    cnName: '反转字符串中的单词',
    enName: 'Reverse Words in a String',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'false',
  },
  152: {
    cnName: '乘积最大子数组',
    enName: 'Maximum Product Subarray',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  153: {
    cnName: '寻找旋转排序数组中的最小值',
    enName: 'Find Minimum in Rotated Sorted Array',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  155: {
    cnName: '最小栈',
    enName: 'Min Stack',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  160: {
    cnName: '相交链表',
    enName: 'Intersection of Two Linked List',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'false',
  },
  162: {
    cnName: '寻找峰值',
    enName: 'Find Peak Element',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  165: {
    cnName: '比较版本号',
    enName: 'Compare Version Numbers',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  166: {
    cnName: '分数到小数',
    enName: 'Fraction to Recurring Decimal',
    difficulty: 'Medium',
    label: '长除法',
    hasThinkings: 'false',
  },
  167: {
    cnName: '两数之和 II',
    enName: 'Two Sum II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  168: {
    cnName: 'Excel 列表名称',
    enName: 'Excel Sheet Column Title',
    difficulty: 'Easy',
    label: '数学方法',
    hasThinkings: 'false',
  },
  169: {
    cnName: '求众数',
    enName: 'Majority Element',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  171: {
    cnName: '表列序号',
    enName: 'Excel Sheet Column Number Excel',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  172: {
    cnName: '阶乘后的零',
    enName: 'Factorial Trailing Zeroes',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  179: {
    cnName: '最大数',
    enName: 'Largest Number',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  189: {
    cnName: '旋转数组',
    enName: 'Rotate Array',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  190: {
    cnName: '颠倒二进制位',
    enName: 'Reverse Bits',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  191: {
    cnName: '位 1 的个数',
    enName: 'Number of 1 Bits',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  198: {
    cnName: '打家劫舍',
    enName: 'House Robber',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  199: {
    cnName: '二叉树的右视图',
    enName: 'Binary Tree Right Side View',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  200: {
    cnName: '岛屿数量',
    enName: 'Number of Islands',
    difficulty: 'Medium',
    label: '图、DFS',
    hasThinkings: 'false',
  },
  202: {
    cnName: '快乐数',
    enName: 'Happy Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  203: {
    cnName: '删除链表中的元素',
    enName: 'Remove Linked List Elements',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  204: {
    cnName: '计数质数',
    enName: 'Count Primes',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  205: {
    cnName: '同构字符串',
    enName: 'Isomorphic Strings',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  206: {
    cnName: '反转链表',
    enName: 'Reverse Linked List',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  207: {
    cnName: '课程表',
    enName: 'Course Schedule',
    difficulty: 'Medium',
    label: '图',
    hasThinkings: 'false',
  },
  208: {
    cnName: '实现Tire（前缀树）',
    enName: 'Implement Tire (Prefix Tree)',
    difficulty: 'Medium',
    label: '前缀树',
    hasThinkings: 'false',
  },
  210: {
    cnName: '课程表 II',
    enName: 'Course Schedule II',
    difficulty: 'Medium',
    label: 'BFS',
    hasThinkings: 'false',
  },
  212: {
    cnName: '单词搜索 II',
    enName: 'Word Search II',
    difficulty: 'Hard',
    label: 'DFS',
    hasThinkings: 'false',
  },
  214: {
    cnName: '最短回文串',
    enName: 'Shortest Palindrome',
    difficulty: 'Hard',
    label: 'KMP',
    hasThinkings: 'false',
  },
  215: {
    cnName: '数组中的第 K 大元素',
    enName: 'Kth Largest Element in an Array',
    difficulty: 'Medium',
    label: '优先队列',
    hasThinkings: 'false',
  },
  216: {
    cnName: '组合总和 III',
    enName: 'Combination Sum III',
    difficulty: 'Medium',
    label: '空间枚举',
    hasThinkings: 'false',
  },
  217: {
    cnName: '存在重复元素',
    enName: 'Contains Duplicate',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  218: {
    cnName: '天际线问题',
    enName: 'The Skyline Problem',
    difficulty: 'Hard',
    label: '二分查找',
    hasThinkings: 'false',
  },
  219: {
    cnName: '存在重复元素 II',
    enName: 'Contains Nearby Duplicate II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  220: {
    cnName: '存在重复元素 III',
    enName: 'Contains Nearby Duplicate III',
    difficulty: 'Hard',
    label: '桶排序',
    hasThinkings: 'false',
  },
  221: {
    cnName: '最大正方形',
    enName: 'Maximal Square',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  225: {
    cnName: '用队列实现栈',
    enName: 'Implement Stack using Queues',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  226: {
    cnName: '翻转二叉树',
    enName: 'Invert Binary Tree',
    difficulty: 'Easy',
    label: '二叉树',
    hasThinkings: 'false',
  },
  227: {
    cnName: '基本计算器 II',
    enName: 'Basic Calculator II',
    difficulty: 'Medium',
    label: '栈',
    hasThinkings: 'false',
  },
  230: {
    cnName: '二叉搜索树中的第 K 小的元素',
    enName: 'Kth Smallest Element in a BST',
    difficulty: 'Medium',
    label: '二叉树',
    hasThinkings: 'false',
  },
  231: {
    cnName: '2 的幂',
    enName: 'Power of Two',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  232: {
    cnName: '用栈实现队列',
    enName: 'Implement Queue using Stacks',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  233: {
    cnName: '数字 1 的个数',
    enName: 'Number of Digit One',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  234: {
    cnName: '回文链表',
    enName: 'Palindrome Linked List',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'false',
  },
  235: {
    cnName: '二叉搜索树的最近公共祖先',
    enName: 'Lowest Common Ancestor of a Binary Search Tree',
    difficulty: 'Medium',
    label: '二叉树',
    hasThinkings: 'false',
  },
  236: {
    cnName: '二叉树的最近公共祖先',
    enName: 'Lowest Common Ancestor of a Binary Tree',
    difficulty: 'Medium',
    label: '二叉树',
    hasThinkings: 'false',
  },
  237: {
    cnName: '删除链表中的节点',
    enName: 'Delete Node in a Linked List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  238: {
    cnName: '除自身以外数组的乘积',
    enName: 'Product of Array Except Self',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'true',
  },
  239: {
    cnName: '滑动窗口最大值',
    enName: 'Slide Window Maximum',
    difficulty: 'Hard',
    label: '子串',
    hasThinkings: 'false',
  },
  240: {
    cnName: '搜索二维矩阵 II',
    enName: 'Search a 2D Matrix II',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  242: {
    cnName: '有效的字母异位词',
    enName: 'Valid Anagram',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  257: {
    cnName: '二叉树的所有路径',
    enName: 'Binary Tree Paths',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  258: {
    cnName: '各位相加',
    enName: 'Add Digits',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  260: {
    cnName: '只出现一次的数字 III',
    enName: 'Single Number III',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  263: {
    cnName: '丑数',
    enName: 'Ugly Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  268: {
    cnName: '缺失数字',
    enName: 'Missing Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  274: {
    cnName: 'H 指数',
    enName: 'H-Index',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  278: {
    cnName: '第一个错误的版本',
    enName: 'First Bad Version',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  279: {
    cnName: '完全平方数',
    enName: 'Perfect Squares',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  283: {
    cnName: '移动零',
    enName: 'Move Zeroes',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'true',
  },
  287: {
    cnName: '寻找重复数',
    enName: 'Find the Duplicate Number',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  289: {
    cnName: '生命游戏',
    enName: 'Game of Life',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  290: {
    cnName: '单词规律',
    enName: 'Word Pattern',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  292: {
    cnName: 'Nim 游戏',
    enName: 'Nim Game',
    difficulty: 'Easy',
    label: '数学',
    hasThinkings: 'false',
  },
  295: {
    cnName: '数据流的中位数',
    enName: 'Find Median from Data Stream',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  297: {
    cnName: '二叉树的序列化与反序列化',
    enName: 'Serialize and Deserialize Binary Tree',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  300: {
    cnName: '最长上升子序列',
    enName: 'Longest Increasing Subsequence',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  301: {
    cnName: '删除无效的括号',
    enName: 'Remove Invalid Parentheses',
    difficulty: 'Hard',
    label: 'BFS',
    hasThinkings: 'false',
  },
  303: {
    cnName: '区域和检索-数组不可变',
    enName: 'Range Sum Query-Immutable',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  309: {
    cnName: '买卖股票的最佳时机含冷冻期',
    enName: 'Best Time to Buy and Sell Stock with Cooldown',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  312: {
    cnName: '戳气球',
    enName: 'Burst Balloons',
    difficulty: 'Hard',
    label: '动态规划',
    hasThinkings: 'false',
  },
  315: {
    cnName: '计算右侧小于当前元素的个数',
    enName: 'Count of Smallest Numbers After Self',
    difficulty: 'Hard',
    label: '归并排序',
    hasThinkings: 'false',
  },
  322: {
    cnName: '零钱兑换',
    enName: 'Coin Change',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  324: {
    cnName: '摆动排序 II',
    enName: 'Wiggle Sort II',
    difficulty: 'Medium',
    label: '排序',
    hasThinkings: 'false',
  },
  326: {
    cnName: '3 的幂',
    enName: 'Power of Three',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  328: {
    cnName: '奇偶链表',
    enName: 'Odd Even Linked List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  329: {
    cnName: '矩阵中的最长递增路径',
    enName: 'Longest Increasing Path in a Matrix',
    difficulty: 'Hard',
    label: '记忆化搜索',
    hasThinkings: 'false',
  },
  332: {
    cnName: '重新安排行程',
    enName: 'Reconstruct Itinerary',
    difficulty: 'Hard',
    label: 'DFS',
    hasThinkings: 'false',
  },
  334: {
    cnName: '递增的三元子序列',
    enName: 'Increasing Triplet Subsequence',
    difficulty: 'Medium',
    label: '贪心、数组',
    hasThinkings: 'false',
  },
  337: {
    cnName: '打家劫舍 III',
    enName: 'House Robber III',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  338: {
    cnName: '比特位计数',
    enName: 'Counting Bits',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  341: {
    cnName: '扁平化嵌套列表迭代器',
    enName: 'Flatten Nested List Iterator',
    difficulty: 'Medium',
    label: '栈',
    hasThinkings: 'false',
  },
  342: {
    cnName: '4 的幂',
    enName: 'Power of Four',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  343: {
    cnName: '整数拆分',
    enName: 'Integer Break',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  344: {
    cnName: '反转字符串',
    enName: 'Reverse String',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  345: {
    cnName: '翻转字符串中的元音字母',
    enName: 'Reverse Vowels of a String',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'false',
  },
  347: {
    cnName: '前 K 个高频元素',
    enName: 'Top K Frequent Elements',
    difficulty: 'Medium',
    label: '桶排序',
    hasThinkings: 'false',
  },
  349: {
    cnName: '两个数组的交集',
    enName: 'Intersection of Two Arrays',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  350: {
    cnName: '两个数组的交集 II',
    enName: 'Intersection of Two Arrays II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  365: {
    cnName: '水壶问题',
    enName: 'Water and Jug Problem',
    difficulty: 'Medium',
    label: '数学方法',
    hasThinkings: 'false',
  },
  371: {
    cnName: '两个整数相加',
    enName: 'Sum of Two Integers',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  373: {
    cnName: '查找和最小的 K 对数字',
    enName: 'Find K Pairs with Smallest Sums',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  374: {
    cnName: '猜数字大小',
    enName: 'Guess Number Higher or lower',
    difficulty: 'Easy',
    label: '二分查找',
    hasThinkings: 'false',
  },
  377: {
    cnName: '组合总和 Ⅳ',
    enName: 'Combination Sum IV',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  378: {
    cnName: '有序矩阵中第 K 小的元素',
    enName: 'Kth Smallest Element in a Sorted Matrix',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  380: {
    cnName: 'O(1)时间插入删除和获取随机元素',
    enName: 'Insert Delete GetRandom O1',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  381: {
    cnName: 'O(1)时间插入删除和获取随机元素-允许重复',
    enName: 'Insert Delete GetRandom O(1) - Duplicates allowed',
    difficulty: 'Hard',
    label: '哈希',
    hasThinkings: 'false',
  },
  383: {
    cnName: '赎金信',
    enName: 'Ransom Note',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  384: {
    cnName: '打乱数组',
    enName: 'Shuffle an Array',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  387: {
    cnName: '字符串中的第一个唯一字符',
    enName: 'First Unique Character in a String',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  389: {
    cnName: '找不同',
    enName: 'Find The Difference',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  392: {
    cnName: '判断子序列',
    enName: 'Is Subsequence',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  394: {
    cnName: '字符串解码',
    enName: 'Decode String',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  395: {
    cnName: '至少有 K 个充数字符的最长子串',
    enName: 'Longest Substring with At Least K Repeating Characters',
    difficulty: 'Medium',
    label: '分治',
    hasThinkings: 'false',
  },
  399: {
    cnName: '除法求值',
    enName: 'Evaluate Division',
    difficulty: 'Medium',
    label: '图、DFS',
    hasThinkings: 'false',
  },
  400: {
    cnName: '第 N 个数字',
    enName: 'Find Nth Digit',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  405: {
    cnName: '转 16 进制',
    enName: 'Convert a Number to Hexadecimal',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  406: {
    cnName: '根据身高重建队列',
    enName: 'Queue Reconstruction by Height',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  409: {
    cnName: '最长回文串',
    enName: 'Longest Palindrome',
    difficulty: '',
    label: '',
    hasThinkings: 'false',
  },
  412: {
    cnName: 'Fizz Buzz',
    enName: 'Fizz Buzz',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'false',
  },
  414: {
    cnName: '第三大的数',
    enName: 'Third Maximum Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  415: {
    cnName: '字符串相加',
    enName: 'Add Strings',
    difficulty: 'Easy',
    label: '模拟',
    hasThinkings: 'false',
  },
  416: {
    cnName: '分割等和子集',
    enName: 'Partition Equal Subset Sum',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  435: {
    cnName: '无重叠区间',
    enName: 'Non-overlapping Intervals',
    difficulty: 'Medium',
    label: '区间集合',
    hasThinkings: 'false',
  },
  437: {
    cnName: '路径总和 III',
    enName: 'Path Sum III',
    difficulty: 'Medium',
    label: '二叉树、DFS',
    hasThinkings: 'false',
  },
  438: {
    cnName: '找到字符串中所有字母异位词',
    enName: 'Find All Anagrams in a String',
    difficulty: 'Medium',
    label: '滑动窗口',
    hasThinkings: 'true',
  },
  440: {
    cnName: '字典序的第 K 小数字',
    enName: 'Kth Smallest in Lexicographical Order',
    difficulty: 'Hard',
    label: '字典树',
    hasThinkings: 'false',
  },
  441: {
    cnName: '排列硬币',
    enName: 'Arranging Coins',
    difficulty: 'Easy',
    label: '二分查找',
    hasThinkings: 'false',
  },
  442: {
    cnName: '数组中重复的数据',
    enName: 'Find All Duplicates in an Array',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  443: {
    cnName: '压缩字符串',
    enName: 'String Compression',
    difficulty: 'Medium',
    label: '字符串、双指针',
    hasThinkings: 'false',
  },
  447: {
    cnName: '回旋镖的数量',
    enName: 'Number of Boomerangs',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  448: {
    cnName: '找到所有数组中消失的数字',
    enName: 'Find All Numbers Disappeared in an Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  450: {
    cnName: '删除二叉搜索树中的节点',
    enName: 'Delete Node in a BST',
    difficulty: 'Medium',
    label: '二叉搜索树',
    hasThinkings: 'false',
  },
  452: {
    cnName: '用最少数量的箭引爆气球',
    enName: 'Minimum Number of Arrows to Burst Balloons',
    difficulty: 'Medium',
    label: '区间集合',
    hasThinkings: 'false',
  },
  454: {
    cnName: '四数相加 II',
    enName: '4Sum II',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  455: {
    cnName: '分发饼干',
    enName: 'Assign Cookies',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  456: {
    cnName: '132 模式',
    enName: '132 Pattern',
    difficulty: 'Medium',
    label: '枚举',
    hasThinkings: 'false',
  },
  458: {
    cnName: '可怜的小猪',
    enName: 'Poor Pigs',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  459: {
    cnName: '重复的子字符串',
    enName: 'Repeated Substring Pattern',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  461: {
    cnName: '汉明距离',
    enName: 'Hamming Distance',
    difficulty: 'Easy',
    label: '位运算',
    hasThinkings: 'false',
  },
  462: {
    cnName: '最小操作次数是数组元素相等II',
    enName: 'Minimum Move to Equal Array Elements II',
    difficulty: 'Medium',
    label: '排序',
    hasThinkings: 'false',
  },
  463: {
    cnName: '岛屿的周长',
    enName: 'Island Perimeter',
    difficulty: 'Easy',
    label: 'DFS',
    hasThinkings: 'false',
  },
  464: {
    cnName: '我能赢吗',
    enName: 'Can I Win',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  485: {
    cnName: '最大连续 1 的个数',
    enName: 'Find Max Consecutive Ones',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  486: {
    cnName: '预测赢家',
    enName: 'Predict the Winner',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  491: {
    cnName: '递增子序列',
    enName: 'Non- decreasing Subsequence',
    difficulty: 'Medium',
    label: 'DFS',
    hasThinkings: 'false',
  },
  494: {
    cnName: '目标和',
    enName: 'Target Sum',
    difficulty: 'Medium',
    label: '回溯',
    hasThinkings: 'false',
  },
  496: {
    cnName: '下一个更大元素 I',
    enName: 'Next Greater Element I',
    difficulty: 'Easy',
    label: '哈希',
    hasThinkings: 'false',
  },
  509: {
    cnName: '斐波那契数',
    enName: 'Fibonacci',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  518: {
    cnName: '零钱兑换 II',
    enName: 'Coin Change II',
    difficulty: 'Medium',
    label: '动态规划',
    hasThinkings: 'false',
  },
  519: {
    cnName: '随机翻转矩阵',
    enName: 'Random Flip Matrix',
    difficulty: 'Medium',
    label: '数组',
    hasThinkings: 'false',
  },
  529: {
    cnName: '扫雷游戏',
    enName: 'Minesweeper',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  538: {
    cnName: '把二叉搜索树转换为累加树',
    enName: 'Convert BST to Greater Tree',
    difficulty: 'Medium',
    label: '二叉树',
    hasThinkings: 'false',
  },
  541: {
    cnName: '反转字符串 II',
    enName: 'Reverse String II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  543: {
    cnName: '二叉树的直径',
    enName: 'Diameter of Binary Tree',
    difficulty: 'Easy',
    label: '二叉树',
    hasThinkings: 'false',
  },
  547: {
    cnName: '省份数量',
    enName: 'Number of Provinces',
    difficulty: 'Medium',
    label: '图、DFS',
    hasThinkings: 'false',
  },
  551: {
    cnName: '学生出勤记录 I',
    enName: 'Student Attendance Record I',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  552: {
    cnName: '学生出勤记录 II',
    enName: 'Student Attendance Record II',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  557: {
    cnName: '反转字符串中的单词 III',
    enName: 'Reverse Words in a String III',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'false',
  },
  560: {
    cnName: '和为 k 的子数组',
    enName: 'Subarray Sum Equals K',
    difficulty: 'Medium',
    label: '子串',
    hasThinkings: 'false',
  },
  561: {
    cnName: '数组拆分',
    enName: 'Array Partition',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  581: {
    cnName: '最短无序连续子数组',
    enName: 'Shortest Unsorted Continuous Subarray',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  589: {
    cnName: 'N叉树的前序遍历',
    enName: 'N-ray Tree Preorder Traversal',
    difficulty: 'Easy',
    label: '二叉树',
    hasThinkings: 'false',
  },
  605: {
    cnName: '种花问题',
    enName: 'Can Place Flowers',
    difficulty: 'Easy',
    label: '贪心',
    hasThinkings: 'false',
  },
  606: {
    cnName: '根据二叉树创建字符串',
    enName: 'Construct String from Binary Tree',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  611: {
    cnName: '有效三角形的个数',
    enName: 'Valid Triangle Number',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'false',
  },
  617: {
    cnName: '合并二叉树',
    enName: 'Merge Two Binary Tree',
    difficulty: 'Easy',
    label: '二叉树',
    hasThinkings: 'false',
  },
  621: {
    cnName: '任务调度器',
    enName: 'Task Scheduler',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  628: {
    cnName: '三个数的最大乘积',
    enName: 'Maximum Product of Three Numbers',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  642: {
    cnName: '设计搜索自动补全系统',
    enName: 'Palindromic Substrings',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  643: {
    cnName: '子数组最大平均数 I',
    enName: 'Maximum Average Subarray I',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  647: {
    cnName: '回文子串',
    enName: 'Palindromic Substrings',
    difficulty: 'Medium',
    label: 'Manacher 算法',
    hasThinkings: 'false',
  },
  649: {
    cnName: 'Dota2 参议院',
    enName: 'Dota2 Senate',
    difficulty: 'Medium',
    label: '队列',
    hasThinkings: 'false',
  },
  653: {
    cnName: '两数之和 IV - 输入二叉搜索树',
    enName: 'Two Sum IV - Input is a BST',
    difficulty: 'Easy',
    label: '二叉搜索树、DFS',
    hasThinkings: 'true',
  },
  657: {
    cnName: '机器人能否返回终点',
    enName: 'Robot Return to Origin',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  665: {
    cnName: '非递减数列',
    enName: 'Non-decreasing Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  668: {
    cnName: '乘法表中的第 K 小的数',
    enName: 'Kth Smallest Number in Multiplication Table',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  670: {
    cnName: '最大交换',
    enName: 'Maximum Swap',
    difficulty: 'Medium',
    label: '贪心',
    hasThinkings: 'false',
  },
  680: {
    cnName: '验证回文串 II',
    enName: 'Valid Palindrome II',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  700: {
    cnName: '二叉搜索树中的搜索',
    enName: 'Search in a Binary Search Tree',
    difficulty: 'Easy',
    label: '二叉搜索树',
    hasThinkings: 'false',
  },
  703: {
    cnName: '数据流中的第 K 大元素',
    enName: 'Kth Largest Element in a Stream',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  704: {
    cnName: '二分查找',
    enName: 'Binary Search',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  709: {
    cnName: '转换成小写字母',
    enName: 'To Lower Case',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  714: {
    cnName: '买卖股票的最佳时机含手续费',
    enName: 'Best Time to Buy and Sell Stock with Transaction Fee',
    difficulty: 'Medium',
    label: '多维动态规划',
    hasThinkings: 'false',
  },
  720: {
    cnName: '词典中最长的单词',
    enName: 'Longest Word in Dictionary',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  724: {
    cnName: '寻找数组的中心索引',
    enName: 'Find Pivot Index',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  735: {
    cnName: '小行星碰撞',
    enName: 'Asteroid Collision',
    difficulty: 'Medium',
    label: '栈',
    hasThinkings: 'false',
  },
  738: {
    cnName: '单调递增的数字',
    enName: 'Monotone Increasing Digits',
    difficulty: 'Medium',
    label: '贪心',
    hasThinkings: 'false',
  },
  739: {
    cnName: '每日温度',
    enName: 'Daily Temperatures',
    difficulty: 'Medium',
    label: '单调栈',
    hasThinkings: 'false',
  },
  746: {
    cnName: '使用最小花费爬楼梯',
    enName: 'Min Cost Climbing Stairs',
    difficulty: 'Easy',
    label: '动态规划',
    hasThinkings: 'true',
  },
  747: {
    cnName: '至少是其他数字两倍的最大数',
    enName: 'Largest Number At Least Twice of Others',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  763: {
    cnName: '划分字母区间',
    enName: 'Partition Labels',
    difficulty: 'Medium',
    label: '贪心',
    hasThinkings: 'false',
  },
  778: {
    cnName: '水位上升的泳池中游泳',
    enName: 'Swim In Rising Water',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  784: {
    cnName: '字母大小写全排列',
    enName: 'Letter Case Permutation',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  790: {
    cnName: '多米诺和托米诺平铺',
    enName: 'Domino and Tromino Tiling',
    difficulty: 'Medium',
    label: '一维动态规划',
    hasThinkings: 'false',
  },
  814: {
    cnName: '二叉树剪枝',
    enName: 'Binary Tree Pruning',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  841: {
    cnName: '钥匙和房间',
    enName: 'Keys and Rooms',
    difficulty: 'Medium',
    label: 'DFS',
    hasThinkings: 'false',
  },
  844: {
    cnName: '比较含退格的字符串',
    enName: 'Backspace Sting Compare',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'false',
  },
  845: {
    cnName: '数组中最长的山脉',
    enName: 'Longest Mountain in Array',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'false',
  },
  860: {
    cnName: '柠檬水找零',
    enName: 'Lemonade Change',
    difficulty: 'Easy',
    label: '贪心',
    hasThinkings: 'false',
  },
  864: {
    cnName: '获取所有钥匙的最短路径',
    enName: 'Shortest Path to Get All Keys',
    difficulty: 'Hard',
    label: 'BFS',
    hasThinkings: 'false',
  },
  867: {
    cnName: '转置矩阵',
    enName: 'Transpose Matrix',
    difficulty: 'Easy',
    label: '模拟',
    hasThinkings: 'false',
  },
  872: {
    cnName: '叶子相似的树',
    enName: 'Leaf-Similar Tree',
    difficulty: 'Easy',
    label: '二叉树、DFS',
    hasThinkings: 'false',
  },
  875: {
    cnName: '爱吃香蕉的珂珂',
    enName: 'Koko Eating Banana',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  901: {
    cnName: '股票价格跨度',
    enName: 'Online Stock Span',
    difficulty: 'Medium',
    label: '单调栈',
    hasThinkings: 'false',
  },
  905: {
    cnName: '按奇偶排序数组',
    enName: 'Sort Array By Parity',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  929: {
    cnName: '独特的电子邮件地址',
    enName: 'Num Unique Emails',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  933: {
    cnName: '最近的请求次数',
    enName: 'Number of Recent Calls',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  941: {
    cnName: '有效的山脉数组',
    enName: 'Valid Mountain Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  942: {
    cnName: '增减字符串匹配',
    enName: 'DI String Match',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  946: {
    cnName: '验证栈序列',
    enName: 'Validate Stack Sequences',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  953: {
    cnName: '验证外星语词典',
    enName: 'Verifying an Alien Dictionary',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  965: {
    cnName: '单值二叉树',
    enName: 'Univalued Binary Tree',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  974: {
    cnName: '和可被 K 整除的子数组',
    enName: 'Subarray Sums Divisible by K',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  977: {
    cnName: '有序数组的平方',
    enName: 'Squares of a Sorted Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  989: {
    cnName: '数组形式的整数加法',
    enName: 'Add to Array-Form of Integer',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  994: {
    cnName: '腐烂的橘子',
    enName: 'Rotting Oranges',
    difficulty: 'Medium',
    label: '图、BFS',
    hasThinkings: 'true',
  },
  1002: {
    cnName: '查找常用字符',
    enName: 'Find Common Characters',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1004: {
    cnName: '最大连续1的个数 III',
    enName: 'Max Consecutive Ones III',
    difficulty: 'Medium',
    label: '滑动窗口',
    hasThinkings: 'false',
  },
  1021: {
    cnName: '删除最外层的括号',
    enName: 'Remove Outer Parentheses',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1022: {
    cnName: '从根到叶的二进制数之和',
    enName: 'Sum of Root To Leaf Binary Numbers',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1053: {
    cnName: '交换一次的先前排列',
    enName: 'Previous Permutation With One Swap',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  1071: {
    cnName: '字符串的最大公因子',
    enName: 'Greatest Common Divisor of Strings',
    difficulty: 'Easy',
    label: '字符串、GCD',
    hasThinkings: 'false',
  },
  1108: {
    cnName: 'IP 地址无效化',
    enName: 'Defanging an Ip Address',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'false',
  },
  1122: {
    cnName: '数组的相对排序',
    enName: 'Relative Sort Array',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  1128: {
    cnName: '等价多米诺骨牌对的数量',
    enName: 'Number of Equivalent Domino Pairs',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  1137: {
    cnName: '第 N 个泰波那契数',
    enName: 'N-th Tribonacci Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  1143: {
    cnName: '最长公共子序列',
    enName: 'Longest Common Subsequence',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  1161: {
    cnName: '最大层内元素和',
    enName: 'Maximum Level Sum of a Binary Tree',
    difficulty: 'Medium',
    label: '二叉树、BFS',
    hasThinkings: 'false',
  },
  1191: {
    cnName: 'K 次串联后最大子数组之和',
    enName: 'K-Concatenation Maximum Sum',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  1200: {
    cnName: '最小绝对差',
    enName: 'Minimum Abs Difference',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1207: {
    cnName: '独一无二的出现次数',
    enName: 'Unique Number of Occurrences',
    difficulty: 'Easy',
    label: '哈希',
    hasThinkings: 'false',
  },
  1217: {
    cnName: '玩筹码',
    enName: 'Minimum Cost to Move Chips to The Same Position',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1227: {
    cnName: '飞机座位分配概率',
    enName: 'Airplane Seat Assignment Probability',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  1260: {
    cnName: '二维网格迁移',
    enName: 'Shift 2D Grid',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1268: {
    cnName: '搜索推荐系统',
    enName: 'Search Suggestion System',
    difficulty: 'Medium',
    label: '前缀树',
    hasThinkings: 'false',
  },
  1289: {
    cnName: '下降路径最小和 II',
    enName: 'Minimum Falling Path Sum II',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  1318: {
    cnName: '或运算的最小翻转次数',
    enName: 'Minimum Flips to Make a OR b Equal to c',
    difficulty: 'Medium',
    label: '位运算',
    hasThinkings: 'false',
  },
  1356: {
    cnName: '根据数字二进制下1的数目排序',
    enName: 'Sort Integers by The Number of 1 Bits',
    difficulty: 'Easy',
    label: '位运算',
    hasThinkings: 'false',
  },
  1365: {
    cnName: '有多少小于当前数字的数字',
    enName: 'How Many Numbers Are Smaller Than the Current Number',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1370: {
    cnName: '上升下降字符串',
    enName: 'Increasing Decreasing String',
    difficulty: 'Easy',
    label: '桶计数',
    hasThinkings: 'true',
  },
  1372: {
    cnName: '二叉树中的最长交错路径',
    enName: 'Longest ZigZag Path in a Binary Tree',
    difficulty: 'Medium',
    label: '二叉树、DFS',
    hasThinkings: 'false',
  },
  1388: {
    cnName: '3n 块披萨',
    enName: 'Pizza With 3n Slices',
    difficulty: 'Hard',
    label: '',
    hasThinkings: 'false',
  },
  1403: {
    cnName: '非递增顺序的最小子序列',
    enName: 'Minimum Subsequence in Non-Increasing Order',
    difficulty: 'Easy',
    label: '贪心',
    hasThinkings: 'false',
  },
  1413: {
    cnName: '逐步求和得到正数的最小值',
    enName: 'Minimum Value to Get Positive Step by Step Sum',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1431: {
    cnName: '拥有最多糖果的孩子',
    enName: 'Kids With the Greatest Number of Candies',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  1446: {
    cnName: '连续字符',
    enName: 'Consecutive Characters',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  1448: {
    cnName: '统计二叉树中好节点的数目',
    enName: 'Count Good Nodes in Binary Tree',
    difficulty: 'Medium',
    label: '二叉树、DFS',
    hasThinkings: 'false',
  },
  1451: {
    cnName: '重新排列句子中的单词',
    enName: 'Rearrange Words in a Sentence',
    difficulty: 'Medium',
    label: '字符串',
    hasThinkings: 'false',
  },
  1456: {
    cnName: '定长子串中元音的最大数目',
    enName: 'Maximum Number of Vowels in a Substring of Given Length',
    difficulty: 'Medium',
    label: '滑动窗口',
    hasThinkings: 'false',
  },
  1466: {
    cnName: '重新规划路线',
    enName: 'Reorder Routes to Make All Paths Lead to the City Zero',
    difficulty: 'Medium',
    label: '图、DFS',
    hasThinkings: 'false',
  },
  1470: {
    cnName: '重新排列数组',
    enName: 'Shuffle the Array',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  1493: {
    cnName: '删掉一个元素以后全为1的最长子数组',
    enName: 'Longest Subarray of 1’s After Deleting One Element',
    difficulty: 'Medium',
    label: '滑动窗口',
    hasThinkings: 'false',
  },
  1518: {
    cnName: '换水问题',
    enName: 'Water Bottles',
    difficulty: 'Easy',
    label: '数学方法',
    hasThinkings: 'false',
  },
  1528: {
    cnName: '重新排列字符串',
    enName: 'Shuffle String',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'false',
  },
  1572: {
    cnName: '矩阵对角线的元素和',
    enName: 'Matrix Diagonal Sum',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1576: {
    cnName: '替换所有的问号',
    enName: 'Replace All ?‘s to Avoid Consecutive Repeating Characters',
    difficulty: 'Easy',
    label: '数组',
    hasThinkings: 'true',
  },
  1640: {
    cnName: '能否连接成数组',
    enName: 'Check Array Formation Through Concatenation',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'false',
  },
  1652: {
    cnName: '拆炸弹',
    enName: 'Defuse the Bomb',
    difficulty: 'Easy',
    label: '滑动窗口',
    hasThinkings: 'true',
  },
  1657: {
    cnName: '确定两个字符串是否接近',
    enName: 'Determine if Two Strings Are Close',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  1679: {
    cnName: 'K 和数对的最大数目',
    enName: 'Max Number of K-Sum Pairs',
    difficulty: 'Medium',
    label: '双指针',
    hasThinkings: 'false',
  },
  1726: {
    cnName: '同积元组',
    enName: 'Tuple with Same Product',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  1732: {
    cnName: '找到最高海拔',
    enName: 'Find the Highest Altitude',
    difficulty: 'Easy',
    label: '前缀和',
    hasThinkings: 'true',
  },
  1768: {
    cnName: '交替合并字符串',
    enName: 'Merge String Alternatively',
    difficulty: 'Easy',
    label: '字符串',
    hasThinkings: 'false',
  },
  1823: {
    cnName: '找出游戏的获胜者',
    enName: 'Find The Winner',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  1926: {
    cnName: '迷宫中离入口最近的出口',
    enName: 'Nearest Exit from Entrance in Maze',
    difficulty: 'Medium',
    label: '图、BFS',
    hasThinkings: 'false',
  },
  1945: {
    cnName: '字符串转化后的各位数字之和',
    enName: 'Sum of Digits of String After Convert',
    difficulty: 'Easy',
    label: '',
    hasThinkings: 'true',
  },
  2028: {
    cnName: '找出缺失的观测数据',
    enName: 'Find Missing Observations',
    difficulty: 'Medium',
    label: '数学方法',
    hasThinkings: 'false',
  },
  2038: {
    cnName: '如果相邻两个颜色均相同则删除当前颜色',
    enName: 'Remove Colored Pieces if Both Neighbors are the Same Color',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'true',
  },
  2095: {
    cnName: '删除链表的中间节点',
    enName: 'Delete the Middle Node of a Linked List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'false',
  },
  2130: {
    cnName: '链表最大孪生和',
    enName: 'Maximum Twin Sum of a Linked List',
    difficulty: 'Medium',
    label: '链表',
    hasThinkings: 'true',
  },
  2215: {
    cnName: '找出两数组的不同',
    enName: 'Find the Difference of Two Arrays',
    difficulty: 'Easy',
    label: '哈希',
    hasThinkings: 'false',
  },
  2300: {
    cnName: '咒语和药水的成功对数',
    enName: 'Successful Pairs of Spells and Potions',
    difficulty: 'Medium',
    label: '二分查找',
    hasThinkings: 'false',
  },
  2336: {
    cnName: '无限集中的最小数字',
    enName: 'Smallest Number in infinite Set',
    difficulty: 'Medium',
    label: '优先队列',
    hasThinkings: 'false',
  },
  2352: {
    cnName: '相等行列对',
    enName: 'Equal Row and Column Pairs',
    difficulty: 'Medium',
    label: '哈希',
    hasThinkings: 'false',
  },
  2390: {
    cnName: '从字符串中移除星号',
    enName: 'Removing Stars From a String',
    difficulty: 'Medium',
    label: '栈',
    hasThinkings: 'false',
  },
  2462: {
    cnName: '雇佣 K 位工人的总代价',
    enName: 'Total Cost to Hire K Workers',
    difficulty: 'Medium',
    label: '优先队列',
    hasThinkings: 'false',
  },
  2512: {
    cnName: '奖励最顶尖的 K 名学生',
    enName: 'Reward Top K Students',
    difficulty: 'Medium',
    label: '',
    hasThinkings: 'false',
  },
  2530: {
    cnName: '执行 K 次操作后的最大分数',
    enName: 'Maximal Score After Applying K Operations',
    difficulty: 'Medium',
    label: '贪心、优先队列',
    hasThinkings: 'false',
  },
  2542: {
    cnName: '最大子序列的分数',
    enName: 'Maximum Subsequence Score',
    difficulty: 'Medium',
    label: '优先队列',
    hasThinkings: 'false',
  },
  2578: {
    cnName: '最小和分割',
    enName: 'Split With Minimum Sum',
    difficulty: 'Easy',
    label: '贪心',
    hasThinkings: 'false',
  },
  2580: {
    cnName: '统计将重叠区间合并成组的方案数',
    enName: 'Count Ways to Group Overlapping Ranges',
    difficulty: 'Medium',
    label: '区间合并',
    hasThinkings: 'false',
  },
  2652: {
    cnName: '倍数求和',
    enName: 'Sum Multiples',
    difficulty: 'Easy',
    label: '哈希',
    hasThinkings: 'true',
  },
  2697: {
    cnName: '字典序最小回文串',
    enName: 'Lexicographically Smallest Palindrome',
    difficulty: 'Easy',
    label: '双指针',
    hasThinkings: 'true',
  },
  2731: {
    cnName: '移动机器人',
    enName: 'Movement of Robots',
    difficulty: 'Medium',
    label: '脑筋急转弯',
    hasThinkings: 'false',
  },
  2760: {
    cnName: '最长奇偶子数组',
    enName: 'Longest Even Odd Subarray With Threshold',
    difficulty: 'Easy',
    label: '动态规划',
    hasThinkings: 'true',
  },
};

module.exports = nameMap;
